// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq3O39rxwyw5L9uEJu0h6oDAXZVpXjzfw',
    appId: '1:440131991319:web:94ca3f1fa82a2a6cf02952',
    messagingSenderId: '440131991319',
    projectId: 'testtaskweb-eafb4',
    authDomain: 'testtaskweb-eafb4.firebaseapp.com',
    storageBucket: 'testtaskweb-eafb4.appspot.com',
    measurementId: 'G-T611P8N4D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg_Ft6q7fxzYEAfFi23cnnM7jGjsdTrFc',
    appId: '1:440131991319:android:490a46366c7fa435f02952',
    messagingSenderId: '440131991319',
    projectId: 'testtaskweb-eafb4',
    storageBucket: 'testtaskweb-eafb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz4iPzjFGirxYqlsg0w2H9FJQpykhb10s',
    appId: '1:440131991319:ios:79867a924ca1a16bf02952',
    messagingSenderId: '440131991319',
    projectId: 'testtaskweb-eafb4',
    storageBucket: 'testtaskweb-eafb4.appspot.com',
    iosBundleId: 'com.example.testTaskWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz4iPzjFGirxYqlsg0w2H9FJQpykhb10s',
    appId: '1:440131991319:ios:79867a924ca1a16bf02952',
    messagingSenderId: '440131991319',
    projectId: 'testtaskweb-eafb4',
    storageBucket: 'testtaskweb-eafb4.appspot.com',
    iosBundleId: 'com.example.testTaskWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq3O39rxwyw5L9uEJu0h6oDAXZVpXjzfw',
    appId: '1:440131991319:web:2588b563f0e517d2f02952',
    messagingSenderId: '440131991319',
    projectId: 'testtaskweb-eafb4',
    authDomain: 'testtaskweb-eafb4.firebaseapp.com',
    storageBucket: 'testtaskweb-eafb4.appspot.com',
    measurementId: 'G-2F6SXC5D9Q',
  );
}
